### ISSUE TITLE
Issue creating autonumber record

### ISSUE THREAD

**Issue by Couchiman** [BESDev/Celedon-Autonumber-RTM#17]
Hi, I downloaded version v1.2 managed and installed it on MS CRM 2016. 

I put basic  parameters:

Entity name: incident
Trigger: Create
Number of Digits: 5
Attribute Name: cfi_numerodecasoceledon
Next Number: 1

Steps are fully working

Error:

Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: System.ArgumentNullException: Value cannot be null.
Parameter name: TrackingId: a24cba97-533a-49c3-b34e-f25641d1134f, Depth: 1, Message: SandboxAppDomainHelper.Execute: Could not create the plug-in interface from the plug-in assembly: Celedon.ValidateAutoNumberDetail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>00000000-0000-0000-0000-000000000000</ActivityId>
  <ErrorCode>-2147220970</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>System.ArgumentNullException: Value cannot be null.
Parameter name: TrackingId: a24cba97-533a-49c3-b34e-f25641d1134f, Depth: 1, Message: SandboxAppDomainHelper.Execute: Could not create the plug-in interface from the plug-in assembly: Celedon.ValidateAutoNumber</Message>
  <Timestamp>2017-11-28T20:47:28.4469581Z</Timestamp>
  <ExceptionSource i:nil="true" />
  <InnerFault i:nil="true" />
  <OriginalException i:nil="true" />
  <TraceText>

[Celedon.AutoNumber: Celedon.ValidateAutoNumber]
[4b9b76ff-6dba-e711-a95e-000d3a301c96: Celedon.ValidateAutoNumber: Create of cel_autonumber]

</TraceText>
</OrganizationServiceFault>

**Comment by tsharp** [comment]
Which version of 2016 is this plugin executing against?

**Comment by Couchiman** [comment]
Issue fixed
