### ISSUE TITLE
Cannot open the solution in Visual Studio 2013, 2015 and 2017

### ISSUE THREAD

**Issue by Dremor** [BESDev/Celedon-Autonumber-RTM#4]
Hello.

I cloned the repo with VS 2017, but VS say that AutoNumber.csproj isn't supported. I tried with VS 2015 and VS 2013, and got the same problem. It also says that "AssemblyInfo.cs" is missing from the AutoNumberUnitTest project.

Best regards

**Comment by tsharp** [comment]
@Dremor Thank-you for this report. I am working on an update right now that updates the tooling used for the solutions. 
Install [CRM Developer Extensions](https://github.com/jlattimer/CRMDeveloperExtensions) and then pull the latest version from develop. This version has been tested for compatibility with Visual Studio 2015.
